"""Provider interface. Two implementations: twins (harness) and real (demo).
The agent only ever talks to this interface, so the harness never touches a real inbox."""
from __future__ import annotations

from typing import Protocol


class ProviderError(Exception):
    def __init__(self, app: str, code: int, msg: str = ""):
        super().__init__(f"{app} {code} {msg}")
        self.app, self.code = app, code


class Providers(Protocol):
    # ---- gmail
    def gmail_find_thread(self, email: str) -> dict | None: ...
    def gmail_reply(self, thread_id: str, to: str, body: str) -> str: ...
    def gmail_send(self, to: str, subject: str, body: str) -> str: ...
    def gmail_sent_count(self) -> int: ...
    def gmail_inbox(self, limit: int = 20) -> list[dict]: ...
    # ---- calendar
    def calendar_list(self, day: str) -> list[dict]: ...
    def calendar_find(self, title_like: str) -> dict | None: ...
    def calendar_upcoming(self, days: int = 14) -> list[dict]: ...
    def calendar_create(self, title: str, start_iso: str, minutes: int = 30) -> str: ...
    def calendar_update(self, event_id: str, start_iso: str) -> str: ...
    def calendar_rename(self, event_id: str, title: str) -> str: ...
    def calendar_count(self) -> int: ...
    # ---- slack
    def slack_post(self, channel: str, text: str) -> str: ...
    def slack_count(self) -> int: ...
    # ---- ledger
    def ledger_append(self, row: dict) -> None: ...
    def ledger_rows(self) -> list[dict]: ...
    # ---- contacts
    def contacts(self) -> list[dict]: ...
